### ISSUE TITLE
non related question

### ISSUE THREAD

**Issue by alexzanderr** [gursi26/pandemic_simulation#1]
hey, very nice project.

i have a question about your readme.

how did you insert the presentation video into the readme ?

more exactly how did you upload your video to `https://user-images.githubusercontent.com/75204369/156892046-7c64ba58-c295-4c62-9b74-b0ea915d30fb.mp4` ?

i knew that you can only do that if you are commenting to an issue by pasting an mp4 into the write section.

is there another way to upload videos to github rather than the above method? or you just pasted the video into some random comment and then you put the url into the readme ?

i would very much appreciate if you help me. thanks./

**Comment by gursi26** [comment]
Hi. You can edit the README.md in the browser itself, drag and drop the video file and it will automatically upload to GitHub and insert a link. The detailed Stackoverflow answer can be found [here](https://stackoverflow.com/a/4279746).

**Comment by alexzanderr** [comment]
wow. thank you.
